language: android
jdk: oraclejdk8
sudo: false

notifications:
  email: false

env:
  global:
   - ANDROID_API_LEVEL=25
   - ANDROID_TARGET=android-24
   - EMULATOR_API_LEVEL=24
   - ANDROID_BUILD_TOOLS_VERSION=25.0.0
   - ANDROID_ABI=armeabi-v7a
   - ANDROID_TAG=google_apis
   - ADB_INSTALL_TIMEOUT=16 # minutes (2 minutes by default)
   - GRADLE_OPTS="-Xms512m -Xmx1024m"

before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI #--tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-window &
  - echo "disablePreDex" >> gradle.properties
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
#install: true

before_script: 
  - chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    #- extra
    #- add-on
    
    #- extra-google-m2repository
    - extra-android-m2repository
    
    # Google Play Services
    #- extra-google-google_play_services
    # Support library
    #- extra-android-support
    - sys-img-$ANDROID_ABI-$ANDROID_TARGET
    
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  
cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache

install:
  # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
  - if test ! -e $HOME/android-sdk-dl/tools_r25.2.5-linux.zip ; then curl https://dl.google.com/android/repository/tools_r25.2.5-linux.zip > $HOME/android-sdk-dl/tools_r25.2.5-linux.zip ; fi
  - unzip -n $HOME/android-sdk-dl/tools_r25.2.5-linux.zip -d $HOME/android-sdk
  # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;25.0.2'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-25'
  - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;android;m2repository'
  #- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;google_play_services'
  #- echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;m2repository'

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew connectedCheck
  
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
